--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pk-test
  region: us-west-2
  version: "1.19" #using the version 1.19 So hopefully it has some vulnerability or at least some warnings.

managedNodeGroups: #aws managed 
  - name: managed-ng
    instanceType: t3.small
    desiredCapacity: 2  
    # By default it is going to take optimized ami if you don't specify the AMI field. Alternatively you can specify your own AMI.

