--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-test #name of the cluster
  region: us-west-2

nodeGroups: #Self managed 
  - name: ng1-public
    instanceType: t3.micro
    desiredCapacity: 2
  
managedNodeGroups: #aws managed 
  - name: ng2-managed
    instanceType: t3.micro
    minSize: 1
    maxSize: 3
    desiredCapacity: 2  